import assert from 'node:assert/strict';
import fs from 'node:fs';
import {applyMatrix,applyStrategy,ruleFields,packMatrices} from '../site/scenario-rules.mjs';
import {ScenarioWorkspace,comparePlans,sensitivity} from '../site/scenario-studio.mjs';
import {analyze,cleanState} from '../site/candidate-engine.mjs';
const data=JSON.parse(fs.readFileSync(new URL('../dist/candidate-model.json',import.meta.url),'utf8'));
const ids=['a','b','c'];
let e=ruleFields({matrix:[{from:'a',to:'b',rate:80},{from:'a',to:'c',rate:80}]},ids);
assert.equal(e.matrix.reduce((s,x)=>s+x.rate,0),100);
assert.deepEqual(applyMatrix([50,30,20],[50,30,20],ids,e.matrix,'transfer'),[0,55,45]);
assert.deepEqual(applyMatrix([50,30,20],[50,30,20],ids,[...e.matrix].reverse(),'transfer'),[0,55,45]);
const loss=applyMatrix([50,30,20],[40,36,24],ids,[{from:'a',to:'c',rate:100}],'loss');
assert.deepEqual(loss,[40,30,30]);
assert.deepEqual(applyMatrix([50,30,20],[50,30,20],ids,e.matrix,'loss'),[50,30,20]);
const fixture={candidates:ids.map((candidate_id,i)=>({candidate_id,mean:[45,40,15][i]}))};
const tactical=applyStrategy([45,40,15],fixture,{strategy:'close',cutoff:10,topSplit:50,tactical:100});
assert.deepEqual(tactical,[48.75,43.75,7.5]);
assert.deepEqual(applyStrategy([45,40,15],fixture,{strategy:'close',cutoff:5,topSplit:50,tactical:100}),[45,40,15]);
assert.deepEqual(applyStrategy([45,40,15],fixture,{strategy:'off',tactical:100}),[45,40,15]);
const r=data.counties.find(r=>r.candidates.length===3),cs=r.candidates.map(c=>c.candidate_id),base=analyze(data),workspace=new ScenarioWorkspace(data,{county:r.name});
const next=cleanState({county:r.name,edits:{[r.race_id]:{boostId:cs[0],boost:-5,from:cs[0],to:cs[1],flow:0,tactical:20,strategy:'close',cutoff:15,topSplit:50,matrix:[{from:cs[1],to:cs[0],rate:20},{from:cs[2],to:cs[0],rate:10}],matrixMode:'transfer'}}},data);
workspace.change(next);assert.deepEqual(workspace.undo().edits,{});assert.deepEqual(workspace.redo(),next);
const packed=packMatrices(next);assert.deepEqual(cleanState(packed,data),next);assert.deepEqual(analyze(data,packed),analyze(data,next));
workspace.duplicate();assert.equal(workspace.active,'B');workspace.change({county:r.name});workspace.use('A');assert.deepEqual(workspace.state,next);
const restored=new ScenarioWorkspace(data,{county:r.name});restored.restore(workspace.serialize());assert.deepEqual(restored.serialize(),workspace.serialize());
assert.ok(comparePlans(data,workspace,r.name,base).includes('三方案並列'));
assert.ok(sensitivity(data,next,next.edits[r.race_id]).includes('敏感度'));
assert.throws(()=>workspace.restore({schema_version:99}));
console.log('Scenario studio: simultaneous transfers, loss redistribution, closeness damping, undo/redo, slots, import and compact URL roundtrip passed');
